/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#3a0a00",
        "on-primary": "#5f1600",
        "inverse-on-surface": "#2e3131",
        "on-tertiary": "#2a3232",
        "on-secondary-container": "#9bbfc0",
        "on-background": "#e1e3e3",
        "on-secondary-fixed": "#002021",
        error: "#ffb4ab",
        "outline-variant": "#5a413a",
        "on-primary-container": "#531200",
        "primary-container": "#f75e2d",
        primary: "#ffb59f",
        "inverse-surface": "#e1e3e3",
        "surface-tint": "#ffb59f",
        "on-surface": "#e1e3e3",
        "tertiary-fixed-dim": "#c0c8c8",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#862300",
        surface: "#111414",
        outline: "#a98a81",
        "on-tertiary-fixed-variant": "#404848",
        "on-tertiary-fixed": "#151d1d",
        "surface-container-low": "#191c1d",
        "secondary-fixed-dim": "#a9cdce",
        "surface-container-high": "#272b2b",
        "on-tertiary-container": "#232b2b",
        "tertiary-container": "#8a9292",
        "surface-dim": "#111414",
        "secondary-fixed": "#c5e9ea",
        "on-surface-variant": "#e2bfb5",
        "surface-container-lowest": "#0b0f0f",
        tertiary: "#c0c8c8",
        "surface-container": "#1d2021",
        "on-secondary-fixed-variant": "#2a4c4d",
        "surface-variant": "#323536",
        "on-secondary": "#123637",
        "secondary-container": "#2d4f50",
        background: "#111414",
        "surface-bright": "#363a3a",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb59f",
        "primary-fixed": "#ffdbd1",
        "on-error-container": "#ffdad6",
        secondary: "#a9cdce",
        "tertiary-fixed": "#dce4e4",
        "surface-container-highest": "#323536",
        "inverse-primary": "#af3100",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "margin-desktop": "64px",
        unit: "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "display-md": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-sm": ["Manrope"],
        "body-md": ["Manrope"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-md": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
